spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:data/copi.db}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.sqlite.JDBC}

  jpa:
    database-platform: com.backend.copi.config.SQLiteDialect
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}

app:
  crypto:
    secret: ${MASTER_KEY:test-secret}

  mysqldump:
    path: ${MYSQLDUMP_PATH:mysqldump}

  pgdump:
    path: ${PGDUMP_PATH:pg_dump}

  pgdumpall:
    path: ${PGDUMPALL_PATH:pg_dumpall}

  backup:
    directory: ${APP_BACKUP_DIR:backups}

server:
  port: ${SERVER_PORT:8080}
