spring:
  datasource:
    url: jdbc:sqlite:copi.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: com.backend.copi.config.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  crypto:
    secret: ${MASTER_KEY}

server:
  port: 8080
